/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Neb
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
#define fori(i, st, en) for(int i = st; i < en; i++)
#define rfori(i, st, en) for(int i = st; i >= en; i--)
#define f first
#define s second
#define pb push_back
using namespace std;
typedef vector<int> vi;
typedef pair<int, int> ii;
typedef long long ll;
typedef vector<ii> vii;

int T, N;
string strs[1010];

class j {
public:
    bool pal(string &in){
        int sz = in.size();
        for(int i = 0; (i<<1) <= in.size(); i++){
            if(in[i] != in[sz-i-1]) return false;
        }
        return true;
    }

    bool perfect(string &a, string &b){
        string tmp = a+b;
        return pal(tmp);
    }

    void solve(std::istream& in, std::ostream& out) {
        in >> T;
        for(int t = 1; t <= T; t++){
            in >> N;
            for(int i = 0; i < N; i++) in >> strs[i];
            int cnt = 0;
            fori(i, 0, N)
                fori(j, 0, N){
                    if(i == j) continue;
                    if(perfect(strs[i], strs[j])) cnt++;
                }
            out << "Case #" << t << ": " << cnt << "\n";
        }
    }
};


int main() {
	j solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
